---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kde-streamer
description: Aurora-based KDE image for TV streaming and media playback.

base-image: ghcr.io/ublue-os/aurora
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - tailscale

  - type: dnf
    install:
      install-weak-deps: false
      packages:
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        - chezmoi
        - just

  - type: dnf
    repos:
      copr:
        - imput/helium
    install:
      install-weak-deps: false
      packages:
        - helium
        - gcc
        - make

  - type: script
    scripts:
      - fix-sysusers.sh
      - build-dotfiles.sh
      - build-keyd.sh

  - type: systemd
    system:
      enabled:
        - uupd.timer
        - kde-streamer-fix-sysusers.service
        - keyd.service
      disabled:
        - rpm-ostreed-automatic.timer

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.bassi.Amberol
          - org.kde.gwenview
          - org.kde.dragonplayer
          - org.kde.kweather
          - org.stellarium.Stellarium
          - org.videolan.VLC
          - com.bitwarden.desktop
          - org.mozilla.firefox
          - org.freedesktop.Platform.ffmpeg-full
      - notify: true
        scope: system
        repo:
          url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
          name: flathub-beta
          title: Flathub Beta
        install:
          - com.stremio.Stremio
