---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kde-streamer
description: Aurora-based KDE image for TV streaming and media playback.

base-image: ghcr.io/ublue-os/aurora
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - tailscale

  - type: script
    scripts:
      - fix-sysusers.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.bassi.Amberol
          - org.gnome.gThumb
      - notify: true
        scope: system
        repo:
          url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
          name: flathub-beta
          title: Flathub Beta
        install:
          - com.stremio.Stremio
